remove travis
all builds fail because .env is missing. It might be possible to still
use travis and work around this problem, but since there are no tests at
the moment, travis is more annoying than helpful.

ERROR: Couldn't find env file: /home/travis/build/NTNUI/kundestyrt-rms/.env